name: shellcheck-isopatch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  action-test:
    name: test action by running it
    runs-on: ubuntu-22.04
    steps:
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v3

      - name: do selftest of the action
        uses: ./
        id: selftest

  release-please:
    permissions:
      contents: write
      pull-requests: write
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs:
      - shellcheck
      - isopatch-test
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag: ${{ steps.release-please.outputs.tag_name }}
      upload_url: ${{ steps.release-please.outputs.upload_url }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: node
          package-name: release-please-action
