name: shellcheck-isopatch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  action-test:
    name: test action by running it
    runs-on: ubuntu-22.04
    steps:
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v3

      - name: do selftest of the action
        uses: ./
        id: selftest
